#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=mish_normal
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=40:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# Your job starts in the directory where you call sbatch
cd $HOME/vnn_dl2

# Activate your environment
source activate dl2
# Run your code
srun python train_cls.py --model vn_pointnet_cls --optimizer Adam --rot z --activ mish --log_dir mish_normal_2 --normal

srun python test_cls.py --model vn_pointnet_cls --activ mish --log_dir mish_normal_2 --rot z --normal
srun python test_cls.py --model vn_pointnet_cls --activ mish --log_dir mish_normal_2 --rot so3 --normal