#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=leaky_relu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=5:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# Your job starts in the directory where you call sbatch
cd $HOME/vnn_dl2
# Activate your environment
source activate dl2
# Run your code
srun python test_cls.py --model vn_pointnet_cls --log_dir 2022-05-24_11-01 --rot z --activ leaky_relu
srun python test_cls.py --model vn_pointnet_cls --log_dir 2022-05-24_11-01 --rot so3 --activ leaky_relu
srun python test_cls.py --model vn_pointnet_cls --log_dir 2022-05-25_12-25 --rot z --activ mish
srun python test_cls.py --model vn_pointnet_cls --log_dir 2022-05-25_12-25 --rot so3 --activ mish